version: "2"

services:
  local-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
  local-wp:
    image: wordpress
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    links:
      - local-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: wordpress